version: '3.8'

services:
  mimi-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./backend:/app/backend  # Mount backend source for hot reload
      - ./vector_db:/app/vector_db  # Mount vector database for persistence
    restart: unless-stopped 